import transliterate from "../dist/transliterator.js"

const amh_testWords_input = [
  "ወንበር",
  "ወንበሬ",
  "ወንበርህ ",
  "ወንበርሽ ",
  "ወንበሩ ",
  "ወንበሯ",
  "ወንበራችን ",
  "ወንበራችሁ",
  "ወንበራቸው ",
  "ወንበሮች",
  "ወንበሮቼ",
  "ወንበሮችህ",
  "ወንበሮችሽ",
  "ወንበሮቹ",
  "ወንበሮቿ",
  "ወንበሮቻችን ",
  "ወንበሮቻችሁ",
  "ወንበሮቻቸው ",
  "ልጅ",
  "የልጅ",
  "ልጆች",
  "ልጆቻችን",
  "ልጆቻቸው",
  "ልጆቻቸውን",
  "ቤቶች",
  "ውል",
  "ጎረቤቶቻችን",
  "ፈለገ",
  "ፈለገችው",
  "ፈላለገ",
  "ሰዳደበ",
  "ቀዳደደ",
  "ሸፋፈነ",
  "ቅጠል",
  "ቅጠሎች",
  "ቅጠላቅጠል",
  "ወጣወጥ",
  "ስለማይለወጥ",
  "ተበላ",
  "ተፈላለገ",
  "ተመካከረ",
  "ትቢተኛነት",
  "ተፎካከረ",
  "ተመሳሰለ",
  "ተስተካከለ", //special case, what has T as prefix?
  "ተንከባከበ", //special case
  "መስተካከል", //special case
  "መንከባከብ",
  "ጠቢብ",
  "ጠባብ",
  "ትምህርት",
  "በኢትዮጵያ",
  "የኢትዮጵያ",
]
const en_testWords = [
  "wenber",
  "wenberE",
  "wenberh",
  "wenberx",
  "wenberu",
  "wenberWa",
  "wenberacn",
  "wenberachu",
  "wenberacew",
  "wenberoc",
  "wenberocE",
  "wenberoch",
  "wenberocx",
  "wenberocu",
  "wenberocWa",
  "wenberocacn",
  "wenberocachu",
  "wenberocacew",
  "lj",
  "yelj",
  "ljoc",
  "ljocacn",
  "ljocacew",
  "ljocacewn",
  "bEtoc",
  "wl",
  "gorebEtocacn",
  "felege",
  "felegecw",
  "felalege",
  "sedadebe",
  "qedadede",
  "xefafene",
  "qTel",
  "qTeloc",
  "qTelaqTel",
  "weTaweT",
  "slemayleweT",
  "tebela",
  "tefelalege",
  "temekakere",
  "tbiteNanet",
  "tefokakere",
  "temesasele",
  "testekakele",
  "tenkebakebe",
  "mestekakel",
  "menkebakeb",
  "Tebib",
  "Tebab",
  "tmhrt",
  "beityoPya",
  "yeityoPya",
]

const en_expected_output = [
  "ወንብኧር",
  "ወንብኧርኤ",
  "ወንብኧርህ",
  "ወንብኧርሽ",
  "ወንብኧርኡ",
  "ወንብኧርዋ",
  "ወንብኧርአችን",
  "ወንብኧርአችሁ",
  "ወንብኧርአችኧው",
  "ወንብኧርኦች",
  "ወንብኧርኦችኤ",
  "ወንብኧርኦችህ",
  "ወንብኧርኦችሽ",
  "ወንብኧርኦችኡ",
  "ወንብኧርኦችዋ",
  "ወንብኧርኦችአችን",
  "ወንብኧርኦችአችሁ",
  "ወንብኧርኦችአችኧው",
  "ልጅ",
  "የልጅ",
  "ልጅኦች",
  "ልጅኦችአችን",
  "ልጅኦችአችኧው",
  "ልጅኦችአችኧውን",
  "ቤቶች",
  "ውል",
  "ጎረቤቶቻችን",
  "ፈለገ",
  "ፈለገችው",
  "ፈላለገ",
  "ሠዳደበ",
  "ቀዳደደ",
  "ሸፋፈነ",
  "ቅጥኧል",
  "ቅጥኧልኦች",
  "ቅጥኧልአቅጠል",
  "ወጣወጥ",
  "ሥልኧምአይለወጥ",
  "ተበላ",
  "ተፈላለገ",
  "ተመካከረ",
  "ትብኢትኧኝአንኧት",
  "ተፎካከረ",
  "ተመሣሠለ",
  "ተሥትኧክአክኧል",
  "ተንክኧብአክኧብ",
  "መሥትኧክአክኧል",
  "መንክኧብአክኧብ",
  "ጠቢብ",
  "ጠባብ",
  "ትምህርት",
  "በኢትዮጵይአ",
  "የኢትዮጵይአ",
]

test("Amharic to ASCII transliterator", () => {
  for (let index = 0; index < amh_testWords_input.length; index++) {
    const amh_input = amh_testWords_input[index]
    const amh_output = en_expected_output[index]
    const english = en_testWords[index]

    expect(transliterate.felig_transliterate(amh_input, "am")).toBe(english)

    expect(transliterate.felig_transliterate(english, "en")).toBe(amh_output)
  }
})
